all:
	RUST_BACKTRACE=1 cargo run --features 'watch serde_type'

run-release:
	RUST_BACKTRACE=1 cargo run --features 'serde_type' --release

rlease:
	cargo build --release --features 'serde_type'

update:
	cargo update

clean:
	cargo clean
